### ISSUE TITLE
Why the fairing Base is limited to 1.5m?

### ISSUE THREAD

**Issue by ToumanLin** [KSP-RO/ProceduralFairings#30]
I remember that in the previous version there's no limit...

**Comment by Baguette420** [comment]
I'm having the same problem, its limited to 1.5 metres. Took hours to update my KSP RO to 1.11 and the fairings are the only problem right now. Also it appears to shrink when I right click on it.

**Comment by DRVeyl** [comment]
KSP.log and minimum reproduction steps, please.
Note that RO does not claim to support 1.11, so not sure how to address that the fairings in that environment are not working as expected.
Also note that ProcFairings now formally uses the PartUpgrades system.  If you had an existing career, you may need to go back to the nodes and unlock them to expand the limits.  If you are in sandbox, there should be no limit.

The upgrades are described in <https://github.com/KSP-RO/ProceduralFairings/blob/master/GameData/ProceduralFairings/PF_Settings.cfg>.  ~~So 1.5m is weird, because that is not a limitation in PF's settings.~~  Edit: 1.5m is the max fairingbase size with no tech unlocks.

**Comment by ToumanLin** [comment]
my game version is 1.11.1
but the mod description said it was compative with 1.11+

**Comment by ToumanLin** [comment]
sadbox

**Comment by DRVeyl** [comment]
> So 1.5m is weird, because that is not a limitation in PF's settings.

Correction: 1.5m *is* the maximum base size when other limits are not unlocked.

PF is marked compatible with 1.11.  RO is not.

In sandbox, you must enable PartUpgrades in the difficulty settings:

![image](https://user-images.githubusercontent.com/25906300/125220239-5db34900-e294-11eb-86f0-18535c014f5b.png)

**Comment by Baguette420** [comment]
Thanks that fixed it :) , I was in sandbox KSP RO 1.11. Everything else worked fine, that was the only problem I was getting. Never used to have to do that in my older 1.8.1 RO sandbox save.

**Comment by ToumanLin** [comment]
thanks, the problem solved :D

**Comment by zllamo** [comment]
I'm having the same problem in 1.10. Not in sandbox and I already have part upgrades enabled. I can't find any nodes that say they upgrade the fairing bases either. I'm using RP-1, if that matters.

**Comment by DRVeyl** [comment]
Do you have an updated RP-1?
RP-1 does not use any of the part upgrades, instead it pre-configures the parts to already have the max/unlimited diameter.

**Comment by zllamo** [comment]
I'm still on RP-1 v1.8. I went through the releases and saw that it isn't compatible with Procedural Fairings v6, so I downgraded to v1.8.3.

**Comment by DRVeyl** [comment]
RP-1 v1.8.1 added support PF v6.
RP-1 v1.9 and 1.9.1 both support KSP 1.8.1+.
RP-1 v1.10 is the first RP-1 release to require KSP 1.10+.

**Comment by zllamo** [comment]
Thank you. I think I figured out the issue. I had KRASH installed, but that seemed to conflict with all the newer versions of RP-1. I uninstalled KRASH and was able to update to RP-1 v1.10 and PF v6.
