### ISSUE TITLE
Sarnus-SIV-3125 Fairing Base (PF) problem with Test Contract

### ISSUE THREAD

**Issue by maddavo** [KSP-RO/ProceduralFairings#35]
Test contract requires part to be tested through staging sequence, but staging the fairings doesn't complete test.  So seems no way to complete Test Contract.
Also part mentions enabling of decoupler in PF module description but there is no button to enable the decoupler in VAB.
Not sure if this part is part of Bluedog DB or PF, since there is a "(PF)" in part title I'm guessing it's probably PF so submitted the issue here.

**Comment by DRVeyl** [comment]
Sarnus parts are in BDB: <https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/master/Gamedata/Bluedog_DB/Parts/Saturn/bluedog_Saturn_S4_3125mFairingBase.cfg>

The (PF) indicates that the part is reconfigured for ProcFairings rather than stock's version of procedural fairings.  There's a compatibility patch in BDB to handle this.

PF doesn't do anything with ModuleTestSubject.  I would re-post and reference on the BDB GH.,

**Comment by DRVeyl** [comment]
I would also guess that the fairings deploying won't be sufficient to pass the contract; the fairingsides in PF are a separate part, and technically you stage them and not the fairing base.  Staging the fairing base is when the payload separates from the base.  This part looks like it lacks a `ModuleDecouple`.  I'm not sure if you can stage a `ModuleCargoBay`?

Anyway, when you post the issue on BDB, link this one here.

**Comment by maddavo** [comment]
Yep, tks.
